services:
  postgres:
    image: postgres:18
    container_name: uptime-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

    restart: unless-stopped

  redis:
    image: redis:8.2-alpine
    container_name: uptime-redis

    command:
      - redis-server
      - --appendonly
      - "yes"
      - --appendfsync
      - everysec

    ports:
      - "127.0.0.1:${REDIS_PORT:-6379}:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
