"""add incidents table

Revision ID: fb04f4b3b9b6
Revises: eefd7aecb38b
Create Date: 2026-08-27 15:34:09.295117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb04f4b3b9b6'
down_revision: Union[str, Sequence[str], None] = 'eefd7aecb38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('monitor_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (status = 'OPEN' AND resolved_at IS NULL)\n            OR\n            (status = 'RESOLVED' AND resolved_at IS NOT NULL)\n            ", name='ck_incidents_status_resolution'),
    sa.CheckConstraint('failure_count >= 1', name='ck_incidents_failure_count_positive'),
    sa.CheckConstraint('resolved_at IS NULL OR resolved_at >= started_at', name='ck_incidents_resolved_after_started'),
    sa.ForeignKeyConstraint(['monitor_id'], ['monitors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_monitor_started_at', 'incidents', ['monitor_id', 'started_at'], unique=False)
    op.create_index('uq_incidents_one_open_per_monitor', 'incidents', ['monitor_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_incidents_one_open_per_monitor', table_name='incidents', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_incidents_monitor_started_at', table_name='incidents')
    op.drop_table('incidents')
    # ### end Alembic commands ###
